const data = {
  products: [
    {
      name: 'Cabeça Fria, Coração Quente',
      slug: 'cabeca-fria-coracao-quente',
      category: 'Shirts',
      image: '/images/imagem01.jpg',
      price: 1000,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Cabeça Fria, Coração Quente',
    },
    {
      name: 'Imponente - a Rec. Do Palmeiras, da Ar. Ao Decat',
      slug: 'imponente',
      category: 'Shirts',
      image: '/images/imagem02.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Imponente',
    },
    {
      name: 'Guardiola Confidencial: Um Ano Dentro Do Bayern De Munique Acompanhando De Perto O Técnico Que Mudou O Futebol Para Sempre',
      slug: 'guardiola-confidencial',
      category: 'Shirts',
      image: '/images/imagem03.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Guardiola Confidencial',
    },
    {
      name: 'A pirâmide invertida: A história da tática no futebol',
      slug: 'piramede-invertida',
      category: 'Pants',
      image: '/images/imagem04.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A pirâmide invertida',
    },
    {
      name: 'Mourinho Rockstar: As Diversas Faces Do Técnico Mais Polêmico Do Mundo',
      slug: 'mourinho-rockstar',
      category: 'Pants',
      image: '/images/imagem05.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Mourinho Rockstar',
    },
    {
      name: 'Escola brasileira de futebol',
      slug: 'escola-brasileira-de-futebol',
      category: 'Pants',
      image: '/images/imagem06.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Escola brasileira de futebol',
    },
  ],
};
export default data;
