const data = {
  products: [
    {
      name: 'Cabeça Fria, Coração Quente',
      slug: 'cabeca-fria-coracao-quente',
      category: 'Esportes',
      image: '/images/imagem01.jpg',
      price: 1000,
      brand:
        ' Vitor Castanheira Abel Ferreira, Carlos Martinho, João Martins, Tiago Costa (Autor), Celso de Campos Jr (Editor).',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description:
        'Escrito em primeira pessoa pela equipa técnica liderada pelo treinador Abel Ferreira, o livro “Cabeça fria, coração quente” faz uma viagem pelos bastidores das conquistas do Palmeiras nas temporadas de 2020 e 2021, culminando no bicampeonato da Copa Libertadores da América. A obra traz as experiências e os desafios enfrentados pelos profissionais portugueses ao longo de seus 13 primeiros meses no futebol brasileiro, com revelações inéditas sobre o pensamento, a filosofia e os métodos de trabalho da comissão – incluindo detalhes inéditos da preparação de 16 jogos-chave, com exercícios e as respectivas análises pré e pós-jogo.',
    },
    {
      name: 'Imponente - a Rec. Do Palmeiras, da Ar. Ao Decat',
      slug: 'imponente',
      category: 'Esportes',
      image: '/images/imagem02.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Imponente',
    },
    {
      name: 'Guardiola Confidencial: Um Ano Dentro Do Bayern De Munique Acompanhando De Perto O Técnico Que Mudou O Futebol Para Sempre',
      slug: 'guardiola-confidencial',
      category: 'Esportes',
      image: '/images/imagem03.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Guardiola Confidencial',
    },
    {
      name: 'A pirâmide invertida: A história da tática no futebol',
      slug: 'piramede-invertida',
      category: 'Esportes',
      image: '/images/imagem04.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A pirâmide invertida',
    },
    {
      name: 'Mourinho Rockstar: As Diversas Faces Do Técnico Mais Polêmico Do Mundo',
      slug: 'mourinho-rockstar',
      category: 'Esportes',
      image: '/images/imagem05.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Mourinho Rockstar',
    },
    {
      name: 'Escola brasileira de futebol',
      slug: 'escola-brasileira-de-futebol',
      category: 'Esportes',
      image: '/images/imagem06.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Escola brasileira de futebol',
    },
  ],
};
export default data;
